name: Build Spigot 1.21.0

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Download BuildTools
        run: |
          curl -o BuildTools.jar https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar

      - name: Run BuildTools
        run: |
          git config --global user.name "BuildBot"
          git config --global user.email "builder@example.com"
          mkdir build
          cd build
          java -jar ../BuildTools.jar --rev 1.21.0

      - name: Upload spigot-api jar
        uses: actions/upload-artifact@v4
        with:
          name: spigot-api-1.21.0
          path: build/Spigot/Spigot-API/target/spigot-api-1.21.0-R0.1-SNAPSHOT.jar
